// <auto-generated />
using Customer.Api.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Customer.Api.Persistence.Migrations;

[DbContext(typeof(CustomerDbContext))]
partial class CustomerDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Customer.Api.Domain.Customer", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedNever()
                .HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");
            b.Property<string>("Email")
                .HasMaxLength(320)
                .HasColumnType("character varying(320)");
            b.Property<string>("FirstName")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");
            b.Property<string>("IdentityProvider")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");
            b.Property<string>("IdentitySubject")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("character varying(255)");
            b.Property<string>("LastName")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");
            b.Property<string>("PhoneNumber")
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");
            b.Property<CustomerStatus>("Status")
                .HasConversion<string>()
                .HasMaxLength(24)
                .HasColumnType("character varying(24)");
            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");
            b.Property<long>("Version")
                .IsConcurrencyToken()
                .HasColumnType("bigint");
            b.HasKey("Id");
            b.HasIndex("IdentityProvider", "IdentitySubject").IsUnique();
            b.ToTable("customers");
        });

        modelBuilder.Entity("Customer.Api.Domain.CustomerAddress", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedNever()
                .HasColumnType("uuid");
            b.Property<string>("City")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");
            b.Property<string>("CountryCode")
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(2)
                .HasColumnType("character(2)");
            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");
            b.Property<Guid>("CustomerId")
                .HasColumnType("uuid");
            b.Property<bool>("IsDefaultBilling")
                .HasColumnType("boolean");
            b.Property<bool>("IsDefaultShipping")
                .HasColumnType("boolean");
            b.Property<string>("Label")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");
            b.Property<string>("Line1")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");
            b.Property<string>("Line2")
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");
            b.Property<string>("PhoneNumber")
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");
            b.Property<string>("PostalCode")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");
            b.Property<string>("RecipientName")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");
            b.Property<string>("Region")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");
            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("CustomerId");
            b.HasIndex("CustomerId", "IsDefaultBilling")
                .IsUnique()
                .HasDatabaseName("UX_customer_addresses_default_billing")
                .HasFilter("\"IsDefaultBilling\"");
            b.HasIndex("CustomerId", "IsDefaultShipping")
                .IsUnique()
                .HasDatabaseName("UX_customer_addresses_default_shipping")
                .HasFilter("\"IsDefaultShipping\"");
            b.ToTable("customer_addresses");
        });

        modelBuilder.Entity("Customer.Api.Domain.CustomerAddress", b =>
        {
            b.HasOne("Customer.Api.Domain.Customer", null)
                .WithMany("Addresses")
                .HasForeignKey("CustomerId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Customer.Api.Domain.Customer", b =>
        {
            b.Navigation("Addresses")
                .UsePropertyAccessMode(PropertyAccessMode.Field);
        });
#pragma warning restore 612, 618
    }
}
