// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Notifications.Api.Persistence;

#nullable disable

namespace Notifications.Api.Persistence.Migrations;

[DbContext(typeof(NotificationDbContext))]
partial class NotificationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("notifications")
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity(
            "Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey",
            entity =>
            {
                entity.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(
                    entity.Property<int>("Id"));

                entity.Property<string>("FriendlyName")
                    .HasColumnType("text");

                entity.Property<string>("Xml")
                    .HasColumnType("text");

                entity.HasKey("Id");

                entity.ToTable("data_protection_keys", "notifications");
            });

        modelBuilder.Entity("Notifications.Api.Persistence.NotificationDelivery", entity =>
        {
            entity.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            entity.Property<DateTimeOffset?>("AcceptedByProviderAtUtc")
                .HasColumnType("timestamp with time zone");

            entity.Property<int>("AttemptCount")
                .HasColumnType("integer");

            entity.Property<DateTimeOffset>("AvailableAtUtc")
                .HasColumnType("timestamp with time zone");

            entity.Property<DateTimeOffset>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone");

            entity.Property<DateTimeOffset?>("DeadLetteredAtUtc")
                .HasColumnType("timestamp with time zone");

            entity.Property<DateTimeOffset>("ExpiresAtUtc")
                .HasColumnType("timestamp with time zone");

            entity.Property<string>("IdempotencyKey")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            entity.Property<string>("LastError")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)");

            entity.Property<Guid?>("LockId")
                .HasColumnType("uuid");

            entity.Property<DateTimeOffset?>("LockedUntilUtc")
                .HasColumnType("timestamp with time zone");

            entity.Property<string>("PayloadHash")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            entity.Property<string>("ProtectedPayload")
                .IsRequired()
                .HasColumnType("text");

            entity.Property<string>("ProviderMessageId")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            entity.Property<string>("Source")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            entity.Property<Guid>("SourceEventId")
                .HasColumnType("uuid");

            entity.Property<string>("Template")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            entity.HasKey("Id");

            entity.HasIndex("AcceptedByProviderAtUtc", "DeadLetteredAtUtc", "AvailableAtUtc")
                .HasDatabaseName("ix_deliveries_dispatch");

            entity.HasIndex("IdempotencyKey")
                .IsUnique()
                .HasDatabaseName("ux_deliveries_idempotency_key");

            entity.HasIndex("Source", "SourceEventId")
                .IsUnique()
                .HasDatabaseName("ux_deliveries_source_event");

            entity.ToTable("deliveries", "notifications");
        });
#pragma warning restore 612, 618
    }
}
