<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Services/Customer/Customer.Api/Customer.Api.csproj" />
    <ProjectReference Include="../../src/Services/Product/Product.Api/Product.Api.csproj" />
    <ProjectReference Include="../../src/Services/ServiceTemplate/ServiceTemplate.Api/ServiceTemplate.Api.csproj" />
    <ProjectReference Include="../../src/Shared/Microservices.Application/Microservices.Application.csproj" />
    <ProjectReference Include="../../src/Shared/Microservices.Contracts/Microservices.Contracts.csproj" />
    <ProjectReference Include="../../src/Shared/Microservices.Messaging/Microservices.Messaging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
