// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payment.Api.Domain;

#nullable disable

namespace Payment.Api.Persistence.Migrations;

[DbContext(typeof(PaymentDbContext))]
partial class PaymentDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
            b.Property<DateTime?>("Consumed").HasColumnType("timestamp with time zone");
            b.Property<Guid>("ConsumerId").HasColumnType("uuid");
            b.Property<DateTime?>("Delivered").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ExpirationTime").HasColumnType("timestamp with time zone");
            b.Property<long?>("LastSequenceNumber").HasColumnType("bigint");
            b.Property<Guid>("LockId").HasColumnType("uuid");
            b.Property<Guid>("MessageId").HasColumnType("uuid");
            b.Property<int>("ReceiveCount").HasColumnType("integer");
            b.Property<DateTime>("Received").HasColumnType("timestamp with time zone");
            b.Property<byte[]>("RowVersion").IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasColumnType("bytea");
            b.HasKey("Id");
            b.HasIndex("Delivered");
            b.ToTable("InboxState");
        });

        modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
        {
            b.Property<long>("SequenceNumber").ValueGeneratedOnAdd().HasColumnType("bigint");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));
            b.Property<string>("Body").IsRequired().HasColumnType("text");
            b.Property<string>("ContentType").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("DestinationAddress").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<DateTime?>("EnqueueTime").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ExpirationTime").HasColumnType("timestamp with time zone");
            b.Property<string>("FaultAddress").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("Headers").HasColumnType("text");
            b.Property<Guid?>("InboxConsumerId").HasColumnType("uuid");
            b.Property<Guid?>("InboxMessageId").HasColumnType("uuid");
            b.Property<Guid?>("InitiatorId").HasColumnType("uuid");
            b.Property<Guid>("MessageId").HasColumnType("uuid");
            b.Property<string>("MessageType").IsRequired().HasColumnType("text");
            b.Property<Guid?>("OutboxId").HasColumnType("uuid");
            b.Property<string>("Properties").HasColumnType("text");
            b.Property<Guid?>("RequestId").HasColumnType("uuid");
            b.Property<string>("ResponseAddress").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<DateTime>("SentTime").HasColumnType("timestamp with time zone");
            b.Property<string>("SourceAddress").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<Guid?>("ConversationId").HasColumnType("uuid");
            b.Property<Guid?>("CorrelationId").HasColumnType("uuid");
            b.HasKey("SequenceNumber");
            b.HasIndex("EnqueueTime");
            b.HasIndex("ExpirationTime");
            b.HasIndex("OutboxId", "SequenceNumber").IsUnique();
            b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber").IsUnique();
            b.ToTable("OutboxMessage");
        });

        modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
        {
            b.Property<Guid>("OutboxId").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTime>("Created").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("Delivered").HasColumnType("timestamp with time zone");
            b.Property<long?>("LastSequenceNumber").HasColumnType("bigint");
            b.Property<Guid>("LockId").HasColumnType("uuid");
            b.Property<byte[]>("RowVersion").IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasColumnType("bytea");
            b.HasKey("OutboxId");
            b.HasIndex("Created");
            b.ToTable("OutboxState");
        });

        modelBuilder.Entity("Payment.Api.Domain.PaymentCustomer", b =>
        {
            b.Property<Guid>("CustomerId").ValueGeneratedNever().HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("IdentityProvider").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.Property<string>("IdentitySubject").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
            b.Property<string>("StripeCustomerId").HasMaxLength(255).HasColumnType("character varying(255)");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<long>("Version").IsConcurrencyToken().HasColumnType("bigint");
            b.HasKey("CustomerId");
            b.HasIndex("IdentityProvider", "IdentitySubject").IsUnique().HasDatabaseName("UX_payment_customers_identity");
            b.HasIndex("StripeCustomerId").IsUnique().HasDatabaseName("UX_payment_customers_stripe_customer_id").HasFilter("\"StripeCustomerId\" IS NOT NULL");
            b.ToTable("payment_customers");
        });

        modelBuilder.Entity("Payment.Api.Domain.SavedPaymentMethod", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("uuid");
            b.Property<string>("Brand").HasMaxLength(32).HasColumnType("character varying(32)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("CustomerId").HasColumnType("uuid");
            b.Property<int?>("ExpMonth").HasColumnType("integer");
            b.Property<int?>("ExpYear").HasColumnType("integer");
            b.Property<bool>("IsDefault").HasColumnType("boolean");
            b.Property<string>("Last4").HasMaxLength(4).HasColumnType("character varying(4)");
            b.Property<string>("ProviderPaymentMethodId").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
            b.Property<SavedPaymentMethodStatus>("Status").HasConversion<string>().HasMaxLength(24).HasColumnType("character varying(24)");
            b.Property<string>("Type").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("WalletType").HasMaxLength(32).HasColumnType("character varying(32)");
            b.HasKey("Id");
            b.HasIndex("CustomerId");
            b.HasIndex("ProviderPaymentMethodId").IsUnique().HasDatabaseName("UX_payment_methods_provider_id");
            b.HasIndex("CustomerId", "IsDefault").IsUnique().HasDatabaseName("UX_payment_methods_default").HasFilter("\"IsDefault\"");
            b.ToTable("payment_methods");
        });

        modelBuilder.Entity("Payment.Api.Persistence.StripeWebhookInboxEntry", b =>
        {
            b.Property<string>("EventId").HasMaxLength(255).HasColumnType("character varying(255)");
            b.Property<int>("AttemptCount").HasColumnType("integer");
            b.Property<string>("EventType").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<string>("LastError").HasMaxLength(2000).HasColumnType("character varying(2000)");
            b.Property<DateTimeOffset?>("NextAttemptAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("ObjectId").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
            b.Property<DateTimeOffset?>("ProcessedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("ProcessingLeaseId").HasColumnType("uuid");
            b.Property<DateTimeOffset?>("ProcessingLeaseExpiresAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("ReceivedAtUtc").HasColumnType("timestamp with time zone");
            b.HasKey("EventId");
            b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc", "ReceivedAtUtc");
            b.ToTable("stripe_webhook_inbox");
        });

        modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
        {
            b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null).WithMany().HasForeignKey("OutboxId");
            b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null).WithMany().HasForeignKey("InboxMessageId", "InboxConsumerId").HasPrincipalKey("MessageId", "ConsumerId");
        });

        modelBuilder.Entity("Payment.Api.Domain.SavedPaymentMethod", b =>
        {
            b.HasOne("Payment.Api.Domain.PaymentCustomer", null).WithMany().HasForeignKey("CustomerId").OnDelete(DeleteBehavior.Restrict).IsRequired();
        });
#pragma warning restore 612, 618
    }
}
